# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_funcionario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
    ]
